name: camera_example
description: Demonstrates how to use the camera plugin.
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  camera_bg:
    path: ../
  flutter:
    sdk: flutter
  flutter_foreground_task: ^8.7.17
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  video_player: ^2.9.5
  flutter_overlay_window: ^0.4.5

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
